# version: '3.9'

# services:
#   # Frontend container
#   frontend:
#     image: nginx:alpine
#     container_name: frontend
#     volumes:
#       - ./frontend:/usr/share/nginx/html:ro
#     ports:
#       - "8080:80"

#   # Backend container
#   backend:
#     image: node:16-alpine
#     container_name: backend
#     depends_on:
#       - db
#     working_dir: /app
#     volumes:
#       - "./backend:/app"
#     environment:
#       - DB_HOST=db
#       - DB_USER=Adil
#       - DB_PASSWORD=abcd123
#       - DB_NAME=votes_Database
#     ports:
#       - "5000:5000"
#     entrypoint: ["sh", "-c"]
#     command: ["npm install && npm start"]

#   # Database container
#   db:
#     image: postgres:latest
#     container_name: db
#     environment:
#       - POSTGRES_USER=Adil
#       - POSTGRES_PASSWORD=abcd123
#       - POSTGRES_DB=votes_Database
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  # Add this line
#     ports:
#       - "5432:5432"

# # Volumes definition
# volumes:
#   postgres_data:





  version: '3.9'
  
  services:
    redis:
      image: redis:alpine
      container_name: redis

    clickcounter:
      image: kodekloud/click-counter
      container_name: clickcounter
      ports:
        - '8085:5000'
